trigger:
  - master
pr:
  autoCancel: true
  branches:
    include:
      - master
pool:
  vmImage: ubuntu-latest
stages:
  - stage: Test
    jobs:
      - job: eclipse_temurin_25
        displayName: Test on Ubuntu with Eclipse Temurin 25
        container: eclipse-temurin:25-jdk
        steps:
          - bash: |
              ./mvnw test -T $(nproc) -ntp
          - task: UseDotNet@2
            displayName: "Use .NET Core sdk"
            condition: not(eq(variables['Build.Reason'], 'PullRequest'))
            inputs:
              version: 6.0.x
              includePreviewVersions: true
          - task: PublishCodeCoverageResults@1
            displayName: "Code coverage"
            condition: not(eq(variables['Build.Reason'], 'PullRequest'))
            inputs:
              codeCoverageTool: "JaCoCo"
              summaryFileLocation: $(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml
              reportDirectory: $(System.DefaultWorkingDirectory)/target/site/jacoco
              #additionalCodeCoverageFiles: # Optional
              failIfCoverageEmpty: true
      - job: maven_3_amazoncorretto_25
        displayName: Test on Amazon Corretto 25
        steps:
          - bash: |
              sed "s/__version__/maven:3-amazoncorretto-25/" -i Dockerfile.amazoncorretto
              docker build -t project -f Dockerfile.amazoncorretto .
              docker run project bash -c "cd /opt/project && mvn test -T $(nproc) -ntp"
