trigger:
  - master
  # TODO remove
  - azure-pipelines-amazon
pool:
  vmImage: ubuntu-latest
stages:
  - stage: Test
    jobs:
      - job: eclipse_temurin_17
        displayName: Test on Ubuntu with Eclipse Temurin 17
        container: eclipse-temurin:17-jdk-focal
        steps:
          - bash: |
              ./mvnw test
          - task: UseDotNet@2
            displayName: "Use .NET Core sdk"
            inputs:
              version: 6.0.x
              includePreviewVersions: true
          - task: PublishCodeCoverageResults@1
            displayName: "Code coverage"
            inputs:
              codeCoverageTool: "JaCoCo"
              summaryFileLocation: $(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml
              reportDirectory: $(System.DefaultWorkingDirectory)/target/site/jacoco
              #additionalCodeCoverageFiles: # Optional
              failIfCoverageEmpty: true
      - job: eclipse_temurin_18
        displayName: Test on Ubuntu with Eclipse Temurin 18
        container: eclipse-temurin:18-jdk-focal
        steps:
          - bash: |
              ./mvnw test
      - job: amazon_corretto_17
        displayName: Test on Amazon Corretto 17
        steps:
          - bash: |
              docker-compose up -f docker-compose-amazon.yml -d
              docker exec project sh -c "cd /opt/project && ./mvnw test"
      - job: amazon_correto_18
        displayName: Test on Amazon Corretto 18
        container: amazoncorretto:18
        steps:
          - bash: |
              ./mvnw test
