trigger:
  - master
pr:
  autoCancel: true
  branches:
    include:
      - master
pool:
  vmImage: ubuntu-latest
stages:
  - stage: Test
    jobs:
      - job: eclipse_temurin_17
        displayName: Test on Ubuntu with Eclipse Temurin 17
        container: eclipse-temurin:17-jdk-focal
        steps:
          - bash: |
              ./mvnw test -T $(nproc)
          - task: UseDotNet@2
            displayName: "Use .NET Core sdk"
            condition: not(eq(variables['Build.Reason'], 'PullRequest'))
            inputs:
              version: 6.0.x
              includePreviewVersions: true
          - task: PublishCodeCoverageResults@1
            displayName: "Code coverage"
            condition: not(eq(variables['Build.Reason'], 'PullRequest'))
            inputs:
              codeCoverageTool: "JaCoCo"
              summaryFileLocation: $(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml
              reportDirectory: $(System.DefaultWorkingDirectory)/target/site/jacoco
              #additionalCodeCoverageFiles: # Optional
              failIfCoverageEmpty: true
      - job: eclipse_temurin_19
        displayName: Test on Ubuntu with Eclipse Temurin 19
        container: eclipse-temurin:19-jdk-focal
        steps:
          - bash: |
              ./mvnw test -T $(nproc)
      - job: amazon_corretto_17
        displayName: Test on Amazon Corretto 17
        steps:
          - bash: |
              sed "s/__version__/amazoncorretto:17/" -i Dockerfile.amazoncorretto
              docker build -t project -f Dockerfile.amazoncorretto .
              docker run project bash -c "cd /opt/project && ./mvnw test -T $(nproc)"
      - job: amazon_correto_19
        displayName: Test on Amazon Corretto 19
        steps:
          - bash: |
              sed "s/__version__/amazoncorretto:19/" -i Dockerfile.amazoncorretto
              docker build -t project -f Dockerfile.amazoncorretto .
              docker run project bash -c "cd /opt/project && ./mvnw test -T $(nproc)"
