trigger:
  - master
pool:
  vmImage: ubuntu-latest
stages:
  - stage: Test
    jobs:
      - job: test-alpine
        displayName: Test on Alpine Linux
        container: eclipse-temurin:17-jdk-alpine
        steps:
          - bash: |
              ./gradlew test
      - job: test-ubuntu
        displayName: Test on Ubuntu
        container: eclipse-temurin:17-jdk-focal
        steps:
          - bash: |
              ./gradlew test
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: "JaCoCo"
              summaryFileLocation: ./jrusty/build/reports/jacoco/test/jacocoTestReport.xml
              #pathToSources: # Optional
              #reportDirectory: # Optional
              #additionalCodeCoverageFiles: # Optional
              failIfCoverageEmpty: true
